language: node_js
node_js:
  - "8.9"
install:
  - npm install
script:
  - npm run sign
env:
  global:
  - GH_REF: github.com/pmario/file-backups.git
if: (branch = sign-it) AND (type = push) AND (sender = pmario)
